Bugfix/ad 55 onsubmit incorrect handling
BitBagCommerce/SyliusAdyenPlugin pull request #38
Opened 2021-11-16 09:48 UTC by er1z

2021-11-16 11:34 UTC, Harvel218 requested changes

2021-11-16 11:34 UTC, Harvel218 commented on src/Resources/public/css/adyen.css
>  }
missing new line at the end, wrong code format in almost whole file.
use this https://www.freeformatter.com/css-beautifier.html
to format css

2021-11-16 11:34 UTC, Harvel218 commented on src/Resources/public/js/checkout.js
Rename the variables (remove the dollar sign, e.g. '$') - this is typical for jquery, and you wrote the vanilla js code, don't confuse the reader! : D

2021-11-16 11:34 UTC, Harvel218 commented on src/Resources/public/js/checkout.js
> +        adyenMethod.querySelector('.adyen-method-grid, .dropin-container').classList.remove('hidden');
this works but it i dont think tis correct.

here querySelector will find First element with matching class - the rest will be missed - i dont know what you want to do here, but if you want just 1 specific element, you shouldnt need 2 classes to find it.

If you want ALL elements with these classes, you should use querySelectorAll, and then in array.forEach((item)=>{
item.classList.remove('hidden')
})

2021-11-16 11:34 UTC, Harvel218 commented on src/Resources/public/js/checkout.js
Line 19: showSubmitButton - schould be toggleSubmitButton or handleSubmitButton - cuz its toggling it's visibility, not just showing :D

2021-11-16 11:34 UTC, Harvel218 commented on src/Resources/public/js/dropin.js
> +        let $form = $container.closest('form');
change variable name (dolar sign thing as above)

2021-11-16 11:34 UTC, Harvel218 commented on src/Resources/public/js/dropin.js
>          const init = () => {
Inside init function you can add if statements, to check if its possible to run functions, and return nothing/error if not - you will not initialize adyen then - but idk if its smthing you need

2021-11-16 16:15 UTC, er1z commented on src/Resources/public/js/checkout.js
> +        adyenMethod.querySelector('.adyen-method-grid, .dropin-container').classList.remove('hidden');
It's intentional — the same code is executed in two different contexts; first `.adyen-method-grid`, second `.dropin-container`, it won't happen for two at once.

2021-11-16 16:15 UTC, er1z commented on src/Resources/public/js/dropin.js
>          const init = () => {
What do you recommend?

2021-11-16 16:17 UTC, er1z commented on src/Resources/public/js/checkout.js
Intentional, we've discussed via DM.

2021-11-16 16:17 UTC, er1z commented on src/Resources/public/css/adyen.css
>  }
phpstorm re-format will be sufficient?

2021-11-17 08:44 UTC, Harvel218 approved these changes

2021-11-17 08:49 UTC, merged